---

- name: Create gedit user theme directory
  ansible.builtin.file:
    path: "{{ gedit_user_theme_path }}"
    state: directory
    mode: "0755"

- name: Copy gedit theme
  ansible.builtin.copy:
    src: "lavanda.xml"
    dest: "{{ gedit_user_theme_path }}/lavanda.xml"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_effective_group_id }}"
    mode: "0755"

...
