---

- name: Create and configure ansible-gedit
  hosts: client

  # TODO local testing only
  # debugger: on_failed

  roles:
    - role: ansible-gedit
      tasks_from: main
      gedit_state: present

...
