---

- name: Verify
  hosts: client

  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:

    - name: Initialize role library
      ansible.builtin.include_role:
        name: ansible-gedit
        tasks_from: init

    - name: Test installed package
      ansible.builtin.assert:
        that:
          - editor_package[ansible_os_family] in ansible_facts.packages
        fail_msg: "Package '{{ editor_package[ansible_os_family] }}' is not installed"
        quiet: true

    - name: Get gedit settings
      loop: "{{ gedit_settings.keys() }}"
      community.general.dconf:
        key: "{{ item }}"
        state: read
      register: dconf_list

    - name: Test gnome settings
      loop: "{{ dconf_list.results }}"
      loop_control:
        loop_var: entry
        label: "{{ entry.item }}"
      ansible.builtin.assert:
        that:
          - entry.value == gedit_settings[entry.item]
        fail_msg: |
          "Expected value '{{ gedit_settings[entry.item] }}'
          but got '{{ entry.value }}' instead for key '{{ entry.item }}'."
        quiet: true

...
